[package]
name = "ownership-validation"
version = "0.1.0"
description = "Solana security example: Ownership Validation"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "ownership_validation"

[dependencies]
anchor-lang = "0.29.0"
